-- Seed 2026-04-21: idempotently repopulate 7 GDD dungeons (3-9) + bosses + abilities.
--
-- Source of truth: `backend/prisma/seed-dungeons.ts` (NEW_DUNGEONS + ABILITY_CATALOG).
-- This .sql mirrors that TS seed 1:1 so a prod / staging snapshot-restore can
-- reseed without needing Node tooling. Generated by `scripts/gen_dungeons_sql.py`.
--
-- When editing: update BOTH `seed-dungeons.ts` AND regenerate this file in the
-- same commit. Use the seed script to bootstrap a new local DB; use this
-- migration to recover production.
--
-- Idempotency: each dungeon block uses ON CONFLICT (slug) DO NOTHING on
-- `dungeons`. If the conflict fires, the RETURNING clause is empty, so the
-- downstream boss + ability inserts silently skip via CROSS JOIN on the empty
-- CTE. Re-running this migration against a DB that already has these dungeons
-- is a no-op.
--
-- Related incidents: Gold Mine (2026-04-11), Stash (2026-04-13), Degon admin
-- role (2026-04-19), Appearance Skins (2026-04-20). See gatekeeper/SKILL.md §6c.

-- ---------------------------------------------------------------------------
-- 3. Fungal Grotto (slug=fungal_grotto)
-- ---------------------------------------------------------------------------

WITH new_dungeon AS (
  INSERT INTO "dungeons" (
    "id", "slug", "name", "description", "lore",
    "level_req", "difficulty", "dungeon_type", "energy_cost",
    "is_active", "sort_order", "gold_reward", "xp_reward",
    "created_at", "updated_at"
  ) VALUES (
    gen_random_uuid(), 'fungal_grotto', 'Fungal Grotto', 'The spores whisper secrets', 'The spores whisper secrets',
    30, 'normal', 'story', 14,
    true, 3, 0, 0,
    NOW(), NOW()
  )
  ON CONFLICT ("slug") DO NOTHING
  RETURNING "id"
),
bosses_to_insert ("name", "boss_type", "level", "hp", "damage", "defense", "speed", "crit_chance", "tagline", "description", "floor_number", "sort_order") AS (
  VALUES
    ('Spore Sprite', 'assassin', 10, 960, 28, 21, 21, 5.0, 'Tiny, glowing, toxic.', 'Tiny, glowing, toxic.', 1, 0),
    ('Mushroom Brute', 'aggressive', 11, 1122, 32, 24, 24, 5.5, 'Thick cap. Thicker skull.', 'Thick cap. Thicker skull.', 2, 1),
    ('Vine Strangler', 'berserker', 12, 1296, 36, 27, 27, 6.0, 'Wraps around legs. Squeezes.', 'Wraps around legs. Squeezes.', 3, 2),
    ('Poison Toad', 'defensive', 12, 1368, 38, 28, 28, 6.5, 'One lick and you see colors.', 'One lick and you see colors.', 4, 3),
    ('Mycelium Golem', 'tank', 13, 1560, 42, 32, 31, 7.0, 'A walking ecosystem.', 'A walking ecosystem.', 5, 4),
    ('Rot Witch', 'defensive', 13, 1638, 45, 34, 33, 7.5, 'Brews potions from decay.', 'Brews potions from decay.', 6, 5),
    ('Fungal Hydra', 'berserker', 14, 1848, 50, 37, 37, 8.0, 'Cut one head — two sprout. Covered in mold.', 'Cut one head — two sprout. Covered in mold.', 7, 6),
    ('Sporeling Hive Mind', 'defensive', 15, 2070, 55, 41, 40, 8.5, 'Thousands of tiny spores, one terrible will.', 'Thousands of tiny spores, one terrible will.', 8, 7),
    ('Blight Treant', 'aggressive', 15, 2160, 57, 43, 42, 9.0, 'The ancient tree fell to corruption.', 'The ancient tree fell to corruption.', 9, 8),
    ('The Overgrowth', 'berserker', 17, 2754, 71, 54, 52, 9.5, 'The grotto itself fights back.', 'The grotto itself fights back.', 10, 9)
),
new_bosses AS (
  INSERT INTO "dungeon_bosses" (
    "id", "dungeon_id", "name", "boss_type", "level",
    "hp", "damage", "defense", "speed", "crit_chance",
    "tagline", "description", "floor_number", "sort_order",
    "created_at", "updated_at"
  )
  SELECT
    gen_random_uuid(), nd."id", b."name", b."boss_type", b."level",
    b."hp", b."damage", b."defense", b."speed", b."crit_chance",
    b."tagline", b."description", b."floor_number", b."sort_order",
    NOW(), NOW()
  FROM new_dungeon nd CROSS JOIN bosses_to_insert b
  RETURNING "id", "name"
),
abilities_to_insert ("boss_name", "name", "ability_type", "damage", "cooldown", "special_effect", "description") AS (
  VALUES
    ('Spore Sprite', 'Poison Cloud', 'magical', 140, 5, 'poison_45_4t', 'Poison cloud. Medium magical damage, 45% poison for 4 turns.'),
    ('Spore Sprite', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Spore Sprite', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Mushroom Brute', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Mushroom Brute', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Mushroom Brute', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Vine Strangler', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Vine Strangler', 'Poison Cloud', 'magical', 140, 5, 'poison_45_4t', 'Poison cloud. Medium magical damage, 45% poison for 4 turns.'),
    ('Vine Strangler', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Poison Toad', 'Poison Cloud', 'magical', 140, 5, 'poison_45_4t', 'Poison cloud. Medium magical damage, 45% poison for 4 turns.'),
    ('Poison Toad', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Poison Toad', 'Regeneration', 'buff', 0, 7, 'regen_8', 'Activates health recovery. +8% boss regeneration.'),
    ('Mycelium Golem', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Mycelium Golem', 'Regeneration', 'buff', 0, 7, 'regen_8', 'Activates health recovery. +8% boss regeneration.'),
    ('Mycelium Golem', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Rot Witch', 'Poison Cloud', 'magical', 140, 5, 'poison_45_4t', 'Poison cloud. Medium magical damage, 45% poison for 4 turns.'),
    ('Rot Witch', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.'),
    ('Rot Witch', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Fungal Hydra', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Fungal Hydra', 'Poison Cloud', 'magical', 140, 5, 'poison_45_4t', 'Poison cloud. Medium magical damage, 45% poison for 4 turns.'),
    ('Fungal Hydra', 'Regeneration', 'buff', 0, 7, 'regen_8', 'Activates health recovery. +8% boss regeneration.'),
    ('Sporeling Hive Mind', 'Chain Lightning', 'magical', 150, 5, '3_hits_stun_15_1t', 'Lightning strikes multiple times. Three magical hits, 15% stun for 1 turn.'),
    ('Sporeling Hive Mind', 'Poison Cloud', 'magical', 140, 5, 'poison_45_4t', 'Poison cloud. Medium magical damage, 45% poison for 4 turns.'),
    ('Sporeling Hive Mind', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Blight Treant', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Blight Treant', 'Regeneration', 'buff', 0, 7, 'regen_8', 'Activates health recovery. +8% boss regeneration.'),
    ('Blight Treant', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('The Overgrowth', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('The Overgrowth', 'Poison Cloud', 'magical', 140, 5, 'poison_45_4t', 'Poison cloud. Medium magical damage, 45% poison for 4 turns.'),
    ('The Overgrowth', 'Regeneration', 'buff', 0, 7, 'regen_8', 'Activates health recovery. +8% boss regeneration.')
)
INSERT INTO "boss_abilities" (
  "id", "boss_id", "name", "ability_type", "damage", "cooldown", "special_effect", "description", "created_at"
)
SELECT
  gen_random_uuid(), nb."id", a."name", a."ability_type", a."damage", a."cooldown", a."special_effect", a."description", NOW()
FROM new_bosses nb JOIN abilities_to_insert a ON nb."name" = a."boss_name";

-- ---------------------------------------------------------------------------
-- 4. Scorched Mines (slug=scorched_mines)
-- ---------------------------------------------------------------------------

WITH new_dungeon AS (
  INSERT INTO "dungeons" (
    "id", "slug", "name", "description", "lore",
    "level_req", "difficulty", "dungeon_type", "energy_cost",
    "is_active", "sort_order", "gold_reward", "xp_reward",
    "created_at", "updated_at"
  ) VALUES (
    gen_random_uuid(), 'scorched_mines', 'Scorched Mines', 'Heat rises from below', 'Heat rises from below',
    35, 'normal', 'story', 16,
    true, 4, 0, 0,
    NOW(), NOW()
  )
  ON CONFLICT ("slug") DO NOTHING
  RETURNING "id"
),
bosses_to_insert ("name", "boss_type", "level", "hp", "damage", "defense", "speed", "crit_chance", "tagline", "description", "floor_number", "sort_order") AS (
  VALUES
    ('Ember Rat', 'assassin', 15, 1620, 43, 32, 32, 5.0, 'Fast, burning, bites.', 'Fast, burning, bites.', 1, 0),
    ('Magma Slime', 'defensive', 16, 1824, 48, 36, 35, 5.5, 'Bubbles and burns everything it touches.', 'Bubbles and burns everything it touches.', 2, 1),
    ('Mine Foreman', 'aggressive', 17, 2040, 52, 40, 39, 6.0, 'Swings a red-hot pickaxe.', 'Swings a red-hot pickaxe.', 3, 2),
    ('Lava Beetle', 'tank', 17, 2142, 55, 42, 41, 6.5, 'Its shell is molten rock.', 'Its shell is molten rock.', 4, 3),
    ('Cinder Elemental', 'aggressive', 18, 2376, 61, 46, 44, 7.0, 'Pure fire given hateful form.', 'Pure fire given hateful form.', 5, 4),
    ('Soot Dragon Whelp', 'berserker', 18, 2484, 63, 48, 46, 7.5, 'Not full-grown. Still very hot.', 'Not full-grown. Still very hot.', 6, 5),
    ('Obsidian Guardian', 'tank', 19, 2736, 69, 53, 51, 8.0, 'Ancient golem fused from volcanic glass.', 'Ancient golem fused from volcanic glass.', 7, 6),
    ('Flame Witch', 'defensive', 20, 3000, 75, 58, 55, 8.5, 'Dances through fire. Controls it.', 'Dances through fire. Controls it.', 8, 7),
    ('Infernal Siege Engine', 'aggressive', 20, 3120, 78, 60, 57, 9.0, 'A mining machine possessed by fire spirits.', 'A mining machine possessed by fire spirits.', 9, 8),
    ('Pyrax the Molten King', 'berserker', 22, 3828, 94, 72, 69, 9.5, 'The mines bow to him. So does the lava.', 'The mines bow to him. So does the lava.', 10, 9)
),
new_bosses AS (
  INSERT INTO "dungeon_bosses" (
    "id", "dungeon_id", "name", "boss_type", "level",
    "hp", "damage", "defense", "speed", "crit_chance",
    "tagline", "description", "floor_number", "sort_order",
    "created_at", "updated_at"
  )
  SELECT
    gen_random_uuid(), nd."id", b."name", b."boss_type", b."level",
    b."hp", b."damage", b."defense", b."speed", b."crit_chance",
    b."tagline", b."description", b."floor_number", b."sort_order",
    NOW(), NOW()
  FROM new_dungeon nd CROSS JOIN bosses_to_insert b
  RETURNING "id", "name"
),
abilities_to_insert ("boss_name", "name", "ability_type", "damage", "cooldown", "special_effect", "description") AS (
  VALUES
    ('Ember Rat', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Ember Rat', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Ember Rat', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Magma Slime', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Magma Slime', 'Regeneration', 'buff', 0, 7, 'regen_8', 'Activates health recovery. +8% boss regeneration.'),
    ('Magma Slime', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Mine Foreman', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Mine Foreman', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Mine Foreman', 'Impale', 'physical', 200, 4, 'bleed_35_3t', 'Precise thrust causing bleeding. Good damage, 35% bleed for 3 turns.'),
    ('Lava Beetle', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Lava Beetle', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Lava Beetle', 'Charge', 'physical', 280, 6, 'first_strike_only', 'Forward rush. Very high damage, only if boss acts first in turn.'),
    ('Cinder Elemental', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Cinder Elemental', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Cinder Elemental', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Soot Dragon Whelp', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Soot Dragon Whelp', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Soot Dragon Whelp', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Obsidian Guardian', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Obsidian Guardian', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Obsidian Guardian', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Flame Witch', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Flame Witch', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Flame Witch', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Infernal Siege Engine', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Infernal Siege Engine', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Infernal Siege Engine', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Pyrax the Molten King', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Pyrax the Molten King', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Pyrax the Molten King', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.')
)
INSERT INTO "boss_abilities" (
  "id", "boss_id", "name", "ability_type", "damage", "cooldown", "special_effect", "description", "created_at"
)
SELECT
  gen_random_uuid(), nb."id", a."name", a."ability_type", a."damage", a."cooldown", a."special_effect", a."description", NOW()
FROM new_bosses nb JOIN abilities_to_insert a ON nb."name" = a."boss_name";

-- ---------------------------------------------------------------------------
-- 5. Frozen Abyss (slug=frozen_abyss)
-- ---------------------------------------------------------------------------

WITH new_dungeon AS (
  INSERT INTO "dungeons" (
    "id", "slug", "name", "description", "lore",
    "level_req", "difficulty", "dungeon_type", "energy_cost",
    "is_active", "sort_order", "gold_reward", "xp_reward",
    "created_at", "updated_at"
  ) VALUES (
    gen_random_uuid(), 'frozen_abyss', 'Frozen Abyss', 'Where even fire freezes', 'Where even fire freezes',
    40, 'normal', 'story', 18,
    true, 5, 0, 0,
    NOW(), NOW()
  )
  ON CONFLICT ("slug") DO NOTHING
  RETURNING "id"
),
bosses_to_insert ("name", "boss_type", "level", "hp", "damage", "defense", "speed", "crit_chance", "tagline", "description", "floor_number", "sort_order") AS (
  VALUES
    ('Frost Wisp', 'assassin', 20, 2400, 60, 46, 44, 5.0, 'A floating shard of cold.', 'A floating shard of cold.', 1, 0),
    ('Ice Wolf', 'berserker', 21, 2646, 66, 50, 48, 5.5, 'Hunts in frozen packs.', 'Hunts in frozen packs.', 2, 1),
    ('Glacier Troll', 'tank', 22, 2904, 72, 55, 52, 6.0, 'Covered in ice. Hits like an avalanche.', 'Covered in ice. Hits like an avalanche.', 3, 2),
    ('Frozen Sentinel', 'tank', 22, 3036, 75, 57, 55, 6.5, 'A soldier trapped in ice, still fighting.', 'A soldier trapped in ice, still fighting.', 4, 3),
    ('Blizzard Harpy', 'assassin', 23, 3312, 81, 62, 59, 7.0, 'Shrieks bring hail.', 'Shrieks bring hail.', 5, 4),
    ('Crystal Golem', 'tank', 23, 3450, 84, 65, 62, 7.5, 'Each facet reflects a different death.', 'Each facet reflects a different death.', 6, 5),
    ('Frost Wyvern', 'berserker', 24, 3744, 91, 70, 67, 8.0, 'Breathes freezing fog.', 'Breathes freezing fog.', 7, 6),
    ('Ice Lich', 'defensive', 25, 4050, 98, 76, 72, 8.5, 'Master of cold magic.', 'Master of cold magic.', 8, 7),
    ('Permafrost Colossus', 'aggressive', 25, 4200, 102, 78, 74, 9.0, 'Hasn''t moved in centuries. Until now.', 'Hasn''t moved in centuries. Until now.', 9, 8),
    ('Glacius the Eternal', 'aggressive', 27, 5022, 120, 93, 88, 9.5, 'Winter incarnate. The abyss itself.', 'Winter incarnate. The abyss itself.', 10, 9)
),
new_bosses AS (
  INSERT INTO "dungeon_bosses" (
    "id", "dungeon_id", "name", "boss_type", "level",
    "hp", "damage", "defense", "speed", "crit_chance",
    "tagline", "description", "floor_number", "sort_order",
    "created_at", "updated_at"
  )
  SELECT
    gen_random_uuid(), nd."id", b."name", b."boss_type", b."level",
    b."hp", b."damage", b."defense", b."speed", b."crit_chance",
    b."tagline", b."description", b."floor_number", b."sort_order",
    NOW(), NOW()
  FROM new_dungeon nd CROSS JOIN bosses_to_insert b
  RETURNING "id", "name"
),
abilities_to_insert ("boss_name", "name", "ability_type", "damage", "cooldown", "special_effect", "description") AS (
  VALUES
    ('Frost Wisp', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Frost Wisp', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Frost Wisp', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Ice Wolf', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Ice Wolf', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Ice Wolf', 'Charge', 'physical', 280, 6, 'first_strike_only', 'Forward rush. Very high damage, only if boss acts first in turn.'),
    ('Glacier Troll', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Glacier Troll', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Glacier Troll', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Frozen Sentinel', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Frozen Sentinel', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Frozen Sentinel', 'Impale', 'physical', 200, 4, 'bleed_35_3t', 'Precise thrust causing bleeding. Good damage, 35% bleed for 3 turns.'),
    ('Blizzard Harpy', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Blizzard Harpy', 'Chain Lightning', 'magical', 150, 5, '3_hits_stun_15_1t', 'Lightning strikes multiple times. Three magical hits, 15% stun for 1 turn.'),
    ('Blizzard Harpy', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Crystal Golem', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Crystal Golem', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Crystal Golem', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Frost Wyvern', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Frost Wyvern', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Frost Wyvern', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Ice Lich', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Ice Lich', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Ice Lich', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Permafrost Colossus', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Permafrost Colossus', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Permafrost Colossus', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Glacius the Eternal', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Glacius the Eternal', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Glacius the Eternal', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.')
)
INSERT INTO "boss_abilities" (
  "id", "boss_id", "name", "ability_type", "damage", "cooldown", "special_effect", "description", "created_at"
)
SELECT
  gen_random_uuid(), nb."id", a."name", a."ability_type", a."damage", a."cooldown", a."special_effect", a."description", NOW()
FROM new_bosses nb JOIN abilities_to_insert a ON nb."name" = a."boss_name";

-- ---------------------------------------------------------------------------
-- 6. Realm of Light (slug=realm_of_light)
-- ---------------------------------------------------------------------------

WITH new_dungeon AS (
  INSERT INTO "dungeons" (
    "id", "slug", "name", "description", "lore",
    "level_req", "difficulty", "dungeon_type", "energy_cost",
    "is_active", "sort_order", "gold_reward", "xp_reward",
    "created_at", "updated_at"
  ) VALUES (
    gen_random_uuid(), 'realm_of_light', 'Realm of Light', 'Where light burns brighter than fire', 'Where light burns brighter than fire',
    45, 'normal', 'story', 20,
    true, 6, 0, 0,
    NOW(), NOW()
  )
  ON CONFLICT ("slug") DO NOTHING
  RETURNING "id"
),
bosses_to_insert ("name", "boss_type", "level", "hp", "damage", "defense", "speed", "crit_chance", "tagline", "description", "floor_number", "sort_order") AS (
  VALUES
    ('Light Sprite', 'assassin', 25, 3300, 80, 62, 58, 5.0, 'Blindingly fast, blindingly bright.', 'Blindingly fast, blindingly bright.', 1, 0),
    ('Radiant Archer', 'assassin', 26, 3588, 86, 67, 63, 5.5, 'Arrows of pure light.', 'Arrows of pure light.', 2, 1),
    ('Crystal Beast', 'defensive', 27, 3888, 93, 72, 68, 6.0, 'Reflects attacks as beams.', 'Reflects attacks as beams.', 3, 2),
    ('Solar Monk', 'berserker', 27, 4050, 97, 75, 71, 6.5, 'Channels the sun through fists.', 'Channels the sun through fists.', 4, 3),
    ('Golden Golem', 'tank', 28, 4368, 104, 81, 76, 7.0, 'Forged from holy metal.', 'Forged from holy metal.', 5, 4),
    ('Seraph Guardian', 'defensive', 28, 4536, 108, 84, 79, 7.5, 'An angel that asks no questions.', 'An angel that asks no questions.', 6, 5),
    ('Prism Dragon', 'berserker', 29, 4872, 115, 90, 84, 8.0, 'Each scale bends light into weapons.', 'Each scale bends light into weapons.', 7, 6),
    ('Light Weaver', 'defensive', 30, 5220, 123, 96, 90, 8.5, 'Stitches reality with radiance.', 'Stitches reality with radiance.', 8, 7),
    ('Solar Colossus', 'tank', 30, 5400, 128, 99, 93, 9.0, 'The temple''s last defender.', 'The temple''s last defender.', 9, 8),
    ('The Heart of the Ray', 'aggressive', 32, 6336, 148, 116, 108, 9.5, 'An artifact given life. Burning judgment.', 'An artifact given life. Burning judgment.', 10, 9)
),
new_bosses AS (
  INSERT INTO "dungeon_bosses" (
    "id", "dungeon_id", "name", "boss_type", "level",
    "hp", "damage", "defense", "speed", "crit_chance",
    "tagline", "description", "floor_number", "sort_order",
    "created_at", "updated_at"
  )
  SELECT
    gen_random_uuid(), nd."id", b."name", b."boss_type", b."level",
    b."hp", b."damage", b."defense", b."speed", b."crit_chance",
    b."tagline", b."description", b."floor_number", b."sort_order",
    NOW(), NOW()
  FROM new_dungeon nd CROSS JOIN bosses_to_insert b
  RETURNING "id", "name"
),
abilities_to_insert ("boss_name", "name", "ability_type", "damage", "cooldown", "special_effect", "description") AS (
  VALUES
    ('Light Sprite', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Light Sprite', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Light Sprite', 'Chain Lightning', 'magical', 150, 5, '3_hits_stun_15_1t', 'Lightning strikes multiple times. Three magical hits, 15% stun for 1 turn.'),
    ('Light Sprite', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Radiant Archer', 'Impale', 'physical', 200, 4, 'bleed_35_3t', 'Precise thrust causing bleeding. Good damage, 35% bleed for 3 turns.'),
    ('Radiant Archer', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Radiant Archer', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Radiant Archer', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Crystal Beast', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Crystal Beast', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Crystal Beast', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Crystal Beast', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Solar Monk', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Solar Monk', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Solar Monk', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Solar Monk', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Golden Golem', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Golden Golem', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Golden Golem', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Golden Golem', 'Regeneration', 'buff', 0, 7, 'regen_8', 'Activates health recovery. +8% boss regeneration.'),
    ('Seraph Guardian', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Seraph Guardian', 'Chain Lightning', 'magical', 150, 5, '3_hits_stun_15_1t', 'Lightning strikes multiple times. Three magical hits, 15% stun for 1 turn.'),
    ('Seraph Guardian', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Seraph Guardian', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Prism Dragon', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Prism Dragon', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Prism Dragon', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Prism Dragon', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Light Weaver', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Light Weaver', 'Chain Lightning', 'magical', 150, 5, '3_hits_stun_15_1t', 'Lightning strikes multiple times. Three magical hits, 15% stun for 1 turn.'),
    ('Light Weaver', 'Regeneration', 'buff', 0, 7, 'regen_8', 'Activates health recovery. +8% boss regeneration.'),
    ('Light Weaver', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Solar Colossus', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Solar Colossus', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Solar Colossus', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Solar Colossus', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('The Heart of the Ray', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('The Heart of the Ray', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('The Heart of the Ray', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('The Heart of the Ray', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.')
)
INSERT INTO "boss_abilities" (
  "id", "boss_id", "name", "ability_type", "damage", "cooldown", "special_effect", "description", "created_at"
)
SELECT
  gen_random_uuid(), nb."id", a."name", a."ability_type", a."damage", a."cooldown", a."special_effect", a."description", NOW()
FROM new_bosses nb JOIN abilities_to_insert a ON nb."name" = a."boss_name";

-- ---------------------------------------------------------------------------
-- 7. Shadow Realm (slug=shadow_realm)
-- ---------------------------------------------------------------------------

WITH new_dungeon AS (
  INSERT INTO "dungeons" (
    "id", "slug", "name", "description", "lore",
    "level_req", "difficulty", "dungeon_type", "energy_cost",
    "is_active", "sort_order", "gold_reward", "xp_reward",
    "created_at", "updated_at"
  ) VALUES (
    gen_random_uuid(), 'shadow_realm', 'Shadow Realm', 'Where the darkness stares back', 'Where the darkness stares back',
    50, 'normal', 'story', 22,
    true, 7, 0, 0,
    NOW(), NOW()
  )
  ON CONFLICT ("slug") DO NOTHING
  RETURNING "id"
),
bosses_to_insert ("name", "boss_type", "level", "hp", "damage", "defense", "speed", "crit_chance", "tagline", "description", "floor_number", "sort_order") AS (
  VALUES
    ('Shadow Wisp', 'assassin', 30, 4320, 102, 79, 74, 5.0, 'A fragment of a nightmare.', 'A fragment of a nightmare.', 1, 0),
    ('Dark Stalker', 'assassin', 31, 4650, 109, 85, 80, 5.5, 'Hunts by sound. Silent footsteps.', 'Hunts by sound. Silent footsteps.', 2, 1),
    ('Void Spider', 'assassin', 32, 4992, 117, 91, 85, 6.0, 'Webs that devour light.', 'Webs that devour light.', 3, 2),
    ('Shade Knight', 'tank', 32, 5184, 122, 94, 89, 6.5, 'Your own silhouette, armored.', 'Your own silhouette, armored.', 4, 3),
    ('Eclipse Wolf', 'berserker', 33, 5544, 130, 101, 94, 7.0, 'Born from a sunless sky.', 'Born from a sunless sky.', 5, 4),
    ('Nightborne Mage', 'defensive', 33, 5742, 134, 104, 98, 7.5, 'Spells woven from absolute darkness.', 'Spells woven from absolute darkness.', 6, 5),
    ('Abyss Hydra', 'berserker', 34, 6120, 142, 111, 104, 8.0, 'Each head a different fear.', 'Each head a different fear.', 7, 6),
    ('Shadow Dragon', 'aggressive', 35, 6510, 151, 118, 110, 8.5, 'Breathes oblivion.', 'Breathes oblivion.', 8, 7),
    ('Void Colossus', 'aggressive', 35, 6720, 156, 122, 114, 9.0, 'Where it steps, nothing remains.', 'Where it steps, nothing remains.', 9, 8),
    ('The Whispering Dark', 'aggressive', 37, 7770, 179, 140, 131, 9.5, 'Not a creature. A place. That hates.', 'Not a creature. A place. That hates.', 10, 9)
),
new_bosses AS (
  INSERT INTO "dungeon_bosses" (
    "id", "dungeon_id", "name", "boss_type", "level",
    "hp", "damage", "defense", "speed", "crit_chance",
    "tagline", "description", "floor_number", "sort_order",
    "created_at", "updated_at"
  )
  SELECT
    gen_random_uuid(), nd."id", b."name", b."boss_type", b."level",
    b."hp", b."damage", b."defense", b."speed", b."crit_chance",
    b."tagline", b."description", b."floor_number", b."sort_order",
    NOW(), NOW()
  FROM new_dungeon nd CROSS JOIN bosses_to_insert b
  RETURNING "id", "name"
),
abilities_to_insert ("boss_name", "name", "ability_type", "damage", "cooldown", "special_effect", "description") AS (
  VALUES
    ('Shadow Wisp', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Shadow Wisp', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Shadow Wisp', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Shadow Wisp', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.'),
    ('Dark Stalker', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Dark Stalker', 'Charge', 'physical', 280, 6, 'first_strike_only', 'Forward rush. Very high damage, only if boss acts first in turn.'),
    ('Dark Stalker', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Dark Stalker', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Void Spider', 'Poison Cloud', 'magical', 140, 5, 'poison_45_4t', 'Poison cloud. Medium magical damage, 45% poison for 4 turns.'),
    ('Void Spider', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Void Spider', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Void Spider', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Shade Knight', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Shade Knight', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Shade Knight', 'Impale', 'physical', 200, 4, 'bleed_35_3t', 'Precise thrust causing bleeding. Good damage, 35% bleed for 3 turns.'),
    ('Shade Knight', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Eclipse Wolf', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Eclipse Wolf', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Eclipse Wolf', 'Charge', 'physical', 280, 6, 'first_strike_only', 'Forward rush. Very high damage, only if boss acts first in turn.'),
    ('Eclipse Wolf', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Nightborne Mage', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Nightborne Mage', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Nightborne Mage', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Nightborne Mage', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.'),
    ('Abyss Hydra', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Abyss Hydra', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Abyss Hydra', 'Poison Cloud', 'magical', 140, 5, 'poison_45_4t', 'Poison cloud. Medium magical damage, 45% poison for 4 turns.'),
    ('Abyss Hydra', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Shadow Dragon', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Shadow Dragon', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Shadow Dragon', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Shadow Dragon', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Void Colossus', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Void Colossus', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Void Colossus', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Void Colossus', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('The Whispering Dark', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('The Whispering Dark', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.'),
    ('The Whispering Dark', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('The Whispering Dark', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.')
)
INSERT INTO "boss_abilities" (
  "id", "boss_id", "name", "ability_type", "damage", "cooldown", "special_effect", "description", "created_at"
)
SELECT
  gen_random_uuid(), nb."id", a."name", a."ability_type", a."damage", a."cooldown", a."special_effect", a."description", NOW()
FROM new_bosses nb JOIN abilities_to_insert a ON nb."name" = a."boss_name";

-- ---------------------------------------------------------------------------
-- 8. Clockwork Citadel (slug=clockwork_citadel)
-- ---------------------------------------------------------------------------

WITH new_dungeon AS (
  INSERT INTO "dungeons" (
    "id", "slug", "name", "description", "lore",
    "level_req", "difficulty", "dungeon_type", "energy_cost",
    "is_active", "sort_order", "gold_reward", "xp_reward",
    "created_at", "updated_at"
  ) VALUES (
    gen_random_uuid(), 'clockwork_citadel', 'Clockwork Citadel', 'Gears never stop turning', 'Gears never stop turning',
    55, 'normal', 'story', 24,
    true, 8, 0, 0,
    NOW(), NOW()
  )
  ON CONFLICT ("slug") DO NOTHING
  RETURNING "id"
),
bosses_to_insert ("name", "boss_type", "level", "hp", "damage", "defense", "speed", "crit_chance", "tagline", "description", "floor_number", "sort_order") AS (
  VALUES
    ('Gear Sprite', 'assassin', 35, 5460, 127, 99, 92, 5.0, 'Tiny, fast, sparking.', 'Tiny, fast, sparking.', 1, 0),
    ('Clockwork Hound', 'berserker', 36, 5832, 135, 105, 98, 5.5, 'Metal teeth, spring-loaded jaws.', 'Metal teeth, spring-loaded jaws.', 2, 1),
    ('Piston Golem', 'tank', 37, 6216, 144, 112, 104, 6.0, 'Each punch backed by steam pressure.', 'Each punch backed by steam pressure.', 3, 2),
    ('Sawblade Dancer', 'assassin', 37, 6438, 149, 116, 108, 6.5, 'Spinning blades, deadly rhythm.', 'Spinning blades, deadly rhythm.', 4, 3),
    ('Tesla Turret', 'defensive', 38, 6840, 158, 123, 115, 7.0, 'Zaps anything that moves.', 'Zaps anything that moves.', 5, 4),
    ('Steam Knight', 'tank', 38, 7068, 163, 127, 118, 7.5, 'Hisses, clanks, annihilates.', 'Hisses, clanks, annihilates.', 6, 5),
    ('Gear Dragon', 'berserker', 39, 7488, 172, 134, 125, 8.0, 'Wings of interlocking cogs.', 'Wings of interlocking cogs.', 7, 6),
    ('Grand Mechanist', 'defensive', 40, 7920, 182, 142, 132, 8.5, 'Builder of nightmares.', 'Builder of nightmares.', 8, 7),
    ('Siege Automaton', 'tank', 40, 8160, 187, 146, 136, 9.0, 'A walking fortress of brass and fury.', 'A walking fortress of brass and fury.', 9, 8),
    ('The Grand Engine', 'aggressive', 42, 9324, 213, 166, 155, 9.5, 'The citadel''s heart. Infinite gears. One mind.', 'The citadel''s heart. Infinite gears. One mind.', 10, 9)
),
new_bosses AS (
  INSERT INTO "dungeon_bosses" (
    "id", "dungeon_id", "name", "boss_type", "level",
    "hp", "damage", "defense", "speed", "crit_chance",
    "tagline", "description", "floor_number", "sort_order",
    "created_at", "updated_at"
  )
  SELECT
    gen_random_uuid(), nd."id", b."name", b."boss_type", b."level",
    b."hp", b."damage", b."defense", b."speed", b."crit_chance",
    b."tagline", b."description", b."floor_number", b."sort_order",
    NOW(), NOW()
  FROM new_dungeon nd CROSS JOIN bosses_to_insert b
  RETURNING "id", "name"
),
abilities_to_insert ("boss_name", "name", "ability_type", "damage", "cooldown", "special_effect", "description") AS (
  VALUES
    ('Gear Sprite', 'Chain Lightning', 'magical', 150, 5, '3_hits_stun_15_1t', 'Lightning strikes multiple times. Three magical hits, 15% stun for 1 turn.'),
    ('Gear Sprite', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Gear Sprite', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Gear Sprite', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Clockwork Hound', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Clockwork Hound', 'Charge', 'physical', 280, 6, 'first_strike_only', 'Forward rush. Very high damage, only if boss acts first in turn.'),
    ('Clockwork Hound', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Clockwork Hound', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Piston Golem', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Piston Golem', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Piston Golem', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Piston Golem', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Sawblade Dancer', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Sawblade Dancer', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Sawblade Dancer', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Sawblade Dancer', 'Impale', 'physical', 200, 4, 'bleed_35_3t', 'Precise thrust causing bleeding. Good damage, 35% bleed for 3 turns.'),
    ('Tesla Turret', 'Chain Lightning', 'magical', 150, 5, '3_hits_stun_15_1t', 'Lightning strikes multiple times. Three magical hits, 15% stun for 1 turn.'),
    ('Tesla Turret', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Tesla Turret', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Tesla Turret', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Steam Knight', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Steam Knight', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Steam Knight', 'Charge', 'physical', 280, 6, 'first_strike_only', 'Forward rush. Very high damage, only if boss acts first in turn.'),
    ('Steam Knight', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Gear Dragon', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Gear Dragon', 'Chain Lightning', 'magical', 150, 5, '3_hits_stun_15_1t', 'Lightning strikes multiple times. Three magical hits, 15% stun for 1 turn.'),
    ('Gear Dragon', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Gear Dragon', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Grand Mechanist', 'Chain Lightning', 'magical', 150, 5, '3_hits_stun_15_1t', 'Lightning strikes multiple times. Three magical hits, 15% stun for 1 turn.'),
    ('Grand Mechanist', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Grand Mechanist', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Grand Mechanist', 'Regeneration', 'buff', 0, 7, 'regen_8', 'Activates health recovery. +8% boss regeneration.'),
    ('Siege Automaton', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Siege Automaton', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Siege Automaton', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Siege Automaton', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('The Grand Engine', 'Chain Lightning', 'magical', 150, 5, '3_hits_stun_15_1t', 'Lightning strikes multiple times. Three magical hits, 15% stun for 1 turn.'),
    ('The Grand Engine', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('The Grand Engine', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('The Grand Engine', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.')
)
INSERT INTO "boss_abilities" (
  "id", "boss_id", "name", "ability_type", "damage", "cooldown", "special_effect", "description", "created_at"
)
SELECT
  gen_random_uuid(), nb."id", a."name", a."ability_type", a."damage", a."cooldown", a."special_effect", a."description", NOW()
FROM new_bosses nb JOIN abilities_to_insert a ON nb."name" = a."boss_name";

-- ---------------------------------------------------------------------------
-- 9. Abyssal Depths (slug=abyssal_depths)
-- ---------------------------------------------------------------------------

WITH new_dungeon AS (
  INSERT INTO "dungeons" (
    "id", "slug", "name", "description", "lore",
    "level_req", "difficulty", "dungeon_type", "energy_cost",
    "is_active", "sort_order", "gold_reward", "xp_reward",
    "created_at", "updated_at"
  ) VALUES (
    gen_random_uuid(), 'abyssal_depths', 'Abyssal Depths', 'Beneath the world, something waits', 'Beneath the world, something waits',
    60, 'normal', 'story', 26,
    true, 9, 0, 0,
    NOW(), NOW()
  )
  ON CONFLICT ("slug") DO NOTHING
  RETURNING "id"
),
bosses_to_insert ("name", "boss_type", "level", "hp", "damage", "defense", "speed", "crit_chance", "tagline", "description", "floor_number", "sort_order") AS (
  VALUES
    ('Depth Crawler', 'assassin', 40, 6720, 154, 120, 112, 5.0, 'Skitters across the ocean floor.', 'Skitters across the ocean floor.', 1, 0),
    ('Angler Horror', 'berserker', 41, 7134, 163, 128, 119, 5.5, 'Its light lures. Its jaws close.', 'Its light lures. Its jaws close.', 2, 1),
    ('Coral Golem', 'tank', 42, 7560, 172, 135, 125, 6.0, 'Living reef with a grudge.', 'Living reef with a grudge.', 3, 2),
    ('Siren', 'defensive', 42, 7812, 178, 140, 130, 6.5, 'Her song drowns reason.', 'Her song drowns reason.', 4, 3),
    ('Kraken Spawn', 'berserker', 43, 8256, 188, 147, 137, 7.0, 'One tentacle from something much larger.', 'One tentacle from something much larger.', 5, 4),
    ('Abyssal Leviathan', 'aggressive', 43, 8514, 194, 152, 141, 7.5, 'A whale-sized predator with a temper.', 'A whale-sized predator with a temper.', 6, 5),
    ('Deep Sea Dragon', 'berserker', 44, 8976, 204, 160, 148, 8.0, 'Scales covered in barnacles and fury.', 'Scales covered in barnacles and fury.', 7, 6),
    ('Drowned Admiral', 'assassin', 45, 9450, 214, 168, 156, 8.5, 'Still commands a ghost fleet.', 'Still commands a ghost fleet.', 8, 7),
    ('Tidal Colossus', 'tank', 45, 9720, 220, 173, 160, 9.0, 'The ocean given legs.', 'The ocean given legs.', 9, 8),
    ('Charybdis the Devourer', 'aggressive', 47, 10998, 249, 195, 181, 9.5, 'The abyss opens. Everything falls in.', 'The abyss opens. Everything falls in.', 10, 9)
),
new_bosses AS (
  INSERT INTO "dungeon_bosses" (
    "id", "dungeon_id", "name", "boss_type", "level",
    "hp", "damage", "defense", "speed", "crit_chance",
    "tagline", "description", "floor_number", "sort_order",
    "created_at", "updated_at"
  )
  SELECT
    gen_random_uuid(), nd."id", b."name", b."boss_type", b."level",
    b."hp", b."damage", b."defense", b."speed", b."crit_chance",
    b."tagline", b."description", b."floor_number", b."sort_order",
    NOW(), NOW()
  FROM new_dungeon nd CROSS JOIN bosses_to_insert b
  RETURNING "id", "name"
),
abilities_to_insert ("boss_name", "name", "ability_type", "damage", "cooldown", "special_effect", "description") AS (
  VALUES
    ('Depth Crawler', 'Poison Cloud', 'magical', 140, 5, 'poison_45_4t', 'Poison cloud. Medium magical damage, 45% poison for 4 turns.'),
    ('Depth Crawler', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Depth Crawler', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Depth Crawler', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Angler Horror', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.'),
    ('Angler Horror', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Angler Horror', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Angler Horror', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Coral Golem', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Coral Golem', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Coral Golem', 'Regeneration', 'buff', 0, 7, 'regen_8', 'Activates health recovery. +8% boss regeneration.'),
    ('Coral Golem', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Siren', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Siren', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.'),
    ('Siren', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Siren', 'Chain Lightning', 'magical', 150, 5, '3_hits_stun_15_1t', 'Lightning strikes multiple times. Three magical hits, 15% stun for 1 turn.'),
    ('Kraken Spawn', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Kraken Spawn', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Kraken Spawn', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Kraken Spawn', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Abyssal Leviathan', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Abyssal Leviathan', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Abyssal Leviathan', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Abyssal Leviathan', 'Regeneration', 'buff', 0, 7, 'regen_8', 'Activates health recovery. +8% boss regeneration.'),
    ('Deep Sea Dragon', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Deep Sea Dragon', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Deep Sea Dragon', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Deep Sea Dragon', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Drowned Admiral', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Drowned Admiral', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.'),
    ('Drowned Admiral', 'Impale', 'physical', 200, 4, 'bleed_35_3t', 'Precise thrust causing bleeding. Good damage, 35% bleed for 3 turns.'),
    ('Drowned Admiral', 'Battle Roar', 'buff', 0, 6, 'str_20_stun_20_1t', 'Deafening roar: buff boss and fear target. +20% STR self, 20% stun 1t.'),
    ('Tidal Colossus', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Tidal Colossus', 'Frost Breath', 'magical', 200, 4, 'slow_30_2t', 'Cold breath. Magical damage, 30% slow for 2 turns.'),
    ('Tidal Colossus', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Tidal Colossus', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Charybdis the Devourer', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.'),
    ('Charybdis the Devourer', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Charybdis the Devourer', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Charybdis the Devourer', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.')
)
INSERT INTO "boss_abilities" (
  "id", "boss_id", "name", "ability_type", "damage", "cooldown", "special_effect", "description", "created_at"
)
SELECT
  gen_random_uuid(), nb."id", a."name", a."ability_type", a."damage", a."cooldown", a."special_effect", a."description", NOW()
FROM new_bosses nb JOIN abilities_to_insert a ON nb."name" = a."boss_name";

-- ---------------------------------------------------------------------------
-- 10. Infernal Throne (slug=infernal_throne)
-- ---------------------------------------------------------------------------

WITH new_dungeon AS (
  INSERT INTO "dungeons" (
    "id", "slug", "name", "description", "lore",
    "level_req", "difficulty", "dungeon_type", "energy_cost",
    "is_active", "sort_order", "gold_reward", "xp_reward",
    "created_at", "updated_at"
  ) VALUES (
    gen_random_uuid(), 'infernal_throne', 'Infernal Throne', 'The final descent into madness', 'The final descent into madness',
    65, 'normal', 'story', 30,
    true, 10, 0, 0,
    NOW(), NOW()
  )
  ON CONFLICT ("slug") DO NOTHING
  RETURNING "id"
),
bosses_to_insert ("name", "boss_type", "level", "hp", "damage", "defense", "speed", "crit_chance", "tagline", "description", "floor_number", "sort_order") AS (
  VALUES
    ('Imp Swarm', 'berserker', 45, 8100, 184, 144, 134, 5.0, 'Small, vicious, everywhere.', 'Small, vicious, everywhere.', 1, 0),
    ('Hellhound Alpha', 'aggressive', 46, 8556, 194, 152, 141, 5.5, 'Three heads, triple the fury.', 'Three heads, triple the fury.', 2, 1),
    ('Flame Demoness', 'defensive', 47, 9024, 204, 160, 148, 6.0, 'Beauty and annihilation.', 'Beauty and annihilation.', 3, 2),
    ('Iron Demon', 'tank', 47, 9306, 210, 165, 153, 6.5, 'Forged in infernal pits.', 'Forged in infernal pits.', 4, 3),
    ('Pit Fiend', 'aggressive', 48, 9792, 221, 173, 160, 7.0, 'Commander of lesser demons.', 'Commander of lesser demons.', 5, 4),
    ('Soul Reaver', 'assassin', 48, 10080, 228, 178, 165, 7.5, 'Steals strength from the fallen.', 'Steals strength from the fallen.', 6, 5),
    ('Infernal Dragon', 'berserker', 49, 10584, 238, 187, 173, 8.0, 'Fire made flesh, fury made scale.', 'Fire made flesh, fury made scale.', 7, 6),
    ('Dark Seraph', 'defensive', 50, 11100, 250, 196, 181, 8.5, 'An angel that chose the wrong side.', 'An angel that chose the wrong side.', 8, 7),
    ('The Throne Guardian', 'tank', 50, 11400, 256, 201, 186, 9.0, 'The last line of defense. Absolute.', 'The last line of defense. Absolute.', 9, 8),
    ('Archfiend Malachar', 'aggressive', 52, 13104, 294, 231, 213, 9.5, 'He sits on the throne. He waits. He wins.', 'He sits on the throne. He waits. He wins.', 10, 9)
),
new_bosses AS (
  INSERT INTO "dungeon_bosses" (
    "id", "dungeon_id", "name", "boss_type", "level",
    "hp", "damage", "defense", "speed", "crit_chance",
    "tagline", "description", "floor_number", "sort_order",
    "created_at", "updated_at"
  )
  SELECT
    gen_random_uuid(), nd."id", b."name", b."boss_type", b."level",
    b."hp", b."damage", b."defense", b."speed", b."crit_chance",
    b."tagline", b."description", b."floor_number", b."sort_order",
    NOW(), NOW()
  FROM new_dungeon nd CROSS JOIN bosses_to_insert b
  RETURNING "id", "name"
),
abilities_to_insert ("boss_name", "name", "ability_type", "damage", "cooldown", "special_effect", "description") AS (
  VALUES
    ('Imp Swarm', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Imp Swarm', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Imp Swarm', 'Haste', 'buff', 0, 7, 'dodge_35_3t', 'Sharp speed increase. +35% dodge for boss for 3 turns.'),
    ('Imp Swarm', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Hellhound Alpha', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Hellhound Alpha', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Hellhound Alpha', 'Charge', 'physical', 280, 6, 'first_strike_only', 'Forward rush. Very high damage, only if boss acts first in turn.'),
    ('Hellhound Alpha', 'Rend', 'physical', 160, 3, 'bleed_40_3t_crit_10', 'Tearing attack with enhanced crit. Medium damage, 40% bleed 3t, +10% crit.'),
    ('Flame Demoness', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Flame Demoness', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Flame Demoness', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Flame Demoness', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.'),
    ('Iron Demon', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Iron Demon', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('Iron Demon', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Iron Demon', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('Pit Fiend', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Pit Fiend', 'Battle Roar', 'buff', 0, 6, 'str_20_stun_20_1t', 'Deafening roar: buff boss and fear target. +20% STR self, 20% stun 1t.'),
    ('Pit Fiend', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Pit Fiend', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Soul Reaver', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.'),
    ('Soul Reaver', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Soul Reaver', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('Soul Reaver', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Infernal Dragon', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Infernal Dragon', 'Tail Swipe', 'physical', 140, 3, '2_hits', 'Double tail strike. Two quick hits with medium multiplier.'),
    ('Infernal Dragon', 'Frenzy', 'physical', 120, 5, '3_hits', 'Series of three quick strikes. Less per hit, high total damage.'),
    ('Infernal Dragon', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Dark Seraph', 'Shadow Bolt', 'magical', 240, 3, 'weaken_20_2t', 'Dark projectile. High magical damage, 20% weaken for 2 turns.'),
    ('Dark Seraph', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Dark Seraph', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.'),
    ('Dark Seraph', 'Dark Shield', 'buff', 0, 6, 'magic_resist_50', 'Dark protection. +50% magic resistance.'),
    ('The Throne Guardian', 'Ground Slam', 'physical', 250, 5, 'stun_25_1t', 'Ground pound, stuns nearby. High damage, 25% stun chance for 1 turn.'),
    ('The Throne Guardian', 'Stone Skin', 'buff', 0, 6, 'armor_60', 'Skin hardens like stone. +60% armor for several turns.'),
    ('The Throne Guardian', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('The Throne Guardian', 'Crushing Blow', 'physical', 220, 4, 'armor_break_30', 'Heavy strike that breaks armor. High physical damage, -30% armor for one hit.'),
    ('Archfiend Malachar', 'Fire Wave', 'magical', 180, 4, '2_hits_burn_25_3t', 'Double fire wave. Two magical hits, 25% burn for 3 turns.'),
    ('Archfiend Malachar', 'Arcane Burst', 'magical', 320, 6, 'none', 'One massive magical explosion. Very high magical damage, no extra effects.'),
    ('Archfiend Malachar', 'Enrage', 'buff', 0, 7, 'str_35', 'Boss enters rage, boosting strength. +35% STR self.'),
    ('Archfiend Malachar', 'Life Drain', 'magical', 200, 5, 'boss_regen_100_2t', 'Drains life and heals boss. Damage to target + 100% boss regen for 2 turns.')
)
INSERT INTO "boss_abilities" (
  "id", "boss_id", "name", "ability_type", "damage", "cooldown", "special_effect", "description", "created_at"
)
SELECT
  gen_random_uuid(), nb."id", a."name", a."ability_type", a."damage", a."cooldown", a."special_effect", a."description", NOW()
FROM new_bosses nb JOIN abilities_to_insert a ON nb."name" = a."boss_name";

