import SwiftUI

/// Manages game asset loading with a 3-tier resolution chain:
///
/// 1. **Bundle** — Assets baked into the app via `Assets.xcassets` (instant, offline)
/// 2. **Disk cache** — Previously downloaded assets in `Caches/GameAssets/` (instant, persists across launches)
/// 3. **Network** — Fetched from Supabase Storage CDN (slow, requires connectivity)
///
/// On app launch, `AssetManager` fetches the manifest from `/api/assets/manifest`,
/// compares with the local cache, and downloads only changed assets in the background.
/// This enables hot-updates — new assets appear without an app store release.
///
/// Usage:
/// ```swift
/// // In SwiftUI view:
/// CachedAssetImage(key: "chest_chain_mail", url: item.imageUrl, fallback: "⚔️")
///
/// // Programmatic:
/// if let image = AssetManager.shared.image(forKey: "chest_chain_mail") { ... }
/// ```
@MainActor @Observable
final class AssetManager {
    static let shared = AssetManager()

    // MARK: - State

    /// Current manifest version (timestamp string from server)
    private(set) var manifestVersion: String = ""

    /// Number of assets currently being downloaded
    private(set) var pendingDownloads: Int = 0

    /// Whether initial manifest sync has completed
    private(set) var hasSynced: Bool = false

    // MARK: - Private

    /// In-memory image cache (key → UIImage) — avoids repeated disk reads
    private var memoryCache: [String: UIImage] = [:]

    /// Maximum number of images to keep in memory cache
    private let memoryCacheLimit = 200

    /// Disk cache directory: Caches/GameAssets/
    private let cacheDirectory: URL

    /// Path to cached manifest JSON
    private let manifestPath: URL

    /// Bundled manifest (from sync-assets.sh, included in app bundle)
    private var bundledManifest: [String: AssetManifestEntry] = [:]

    /// Remote manifest (from /api/assets/manifest)
    private var remoteManifest: [String: AssetManifestEntry] = [:]

    /// Active download tasks (key → Task) to avoid duplicate downloads
    private var activeDownloads: [String: Task<UIImage?, Never>] = [:]

    /// URLSession with disk caching disabled (we manage our own cache)
    private let downloadSession: URLSession

    // MARK: - Init

    private init() {
        let caches = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSTemporaryDirectory())
        self.cacheDirectory = caches.appendingPathComponent("GameAssets", isDirectory: true)
        self.manifestPath = cacheDirectory.appendingPathComponent("manifest.json")

        // Create cache directory if needed
        try? FileManager.default.createDirectory(at: cacheDirectory, withIntermediateDirectories: true)

        // URLSession without HTTP cache (we cache to disk ourselves)
        let config = URLSessionConfiguration.default
        config.requestCachePolicy = .reloadIgnoringLocalCacheData
        config.urlCache = nil
        config.timeoutIntervalForRequest = 30
        config.httpMaximumConnectionsPerHost = 4
        self.downloadSession = URLSession(configuration: config)

        // Load cached manifest from disk
        loadCachedManifest()

        // Load bundled manifest (generated by sync-assets.sh)
        loadBundledManifest()
    }

    // MARK: - Public API

    /// Resolve an image by asset key, with optional URL fallback.
    /// Returns immediately from bundle/cache, or nil if not available yet.
    func image(forKey key: String?) -> UIImage? {
        guard let key, !key.isEmpty else { return nil }

        // 1. Memory cache (fastest)
        if let cached = memoryCache[key] {
            return cached
        }

        // 2. Bundle asset
        if let bundled = UIImage(named: key) {
            addToMemoryCache(key: key, image: bundled)
            return bundled
        }

        // 3. Disk cache
        if let diskImage = loadFromDiskCache(key: key) {
            addToMemoryCache(key: key, image: diskImage)
            return diskImage
        }

        return nil
    }

    /// Start downloading an asset if not already cached. Returns the image once ready.
    /// Call this from `CachedAssetImage` to trigger background fetch.
    func fetchIfNeeded(key: String?, url: String?) async -> UIImage? {
        // Derive cache key: explicit key, or filename from URL (e.g. "chest_chain_mail" from ".../chest_chain_mail.png")
        let cacheKey: String? = {
            if let key, !key.isEmpty { return key }
            if let urlStr = url, let urlObj = URL(string: urlStr) {
                let filename = urlObj.deletingPathExtension().lastPathComponent
                return filename.isEmpty ? nil : filename
            }
            return nil
        }()

        guard let cacheKey, !cacheKey.isEmpty else { return nil }

        // Check caches first
        if let cached = image(forKey: cacheKey) {
            return cached
        }

        // Resolve URL from explicit URL or manifest
        let resolvedURL: URL? = {
            if let urlStr = url, let u = URL(string: urlStr) { return u }
            if let entry = remoteManifest[cacheKey] ?? bundledManifest[cacheKey] {
                return URL(string: entry.url)
            }
            return nil
        }()

        guard let downloadURL = resolvedURL else { return nil }

        // Deduplicate concurrent downloads for the same key
        if let existing = activeDownloads[cacheKey] {
            return await existing.value
        }

        let task = Task<UIImage?, Never> { [weak self] in
            guard let self else { return nil }
            let result = await self.downloadAndCache(key: cacheKey, url: downloadURL)
            await MainActor.run {
                _ = self.activeDownloads.removeValue(forKey: cacheKey)
            }
            return result
        }

        activeDownloads[cacheKey] = task
        pendingDownloads = activeDownloads.count
        return await task.value
    }

    /// Sync with remote manifest — call on app launch.
    /// Downloads only assets that are new or changed since last sync.
    func syncWithServer() async {
        guard let manifestURL = URL(string: "\(AppConstants.apiBaseURL)/assets/manifest") else {
            hasSynced = true
            return
        }

        do {
            let (data, response) = try await downloadSession.data(from: manifestURL)

            guard let httpResponse = response as? HTTPURLResponse,
                  httpResponse.statusCode == 200 else {
                hasSynced = true
                return
            }

            let manifest = try JSONDecoder().decode(AssetManifestResponse.self, from: data)

            // Build lookup
            var newManifest: [String: AssetManifestEntry] = [:]
            for entry in manifest.assets {
                newManifest[entry.key] = entry
            }

            // Find assets that need downloading (not in bundle AND not in disk cache with correct size)
            var toDownload: [(key: String, url: URL)] = []
            for (key, entry) in newManifest {
                // Skip if in bundle
                if UIImage(named: key) != nil { continue }

                // Check disk cache
                let cached = diskCacheFile(forKey: key)
                if FileManager.default.fileExists(atPath: cached.path) {
                    // Check size match
                    let attrs = try? FileManager.default.attributesOfItem(atPath: cached.path)
                    let localSize = attrs?[.size] as? Int ?? 0
                    if localSize == entry.size { continue } // Up to date
                }

                if let url = URL(string: entry.url) {
                    toDownload.append((key: key, url: url))
                }
            }

            remoteManifest = newManifest
            manifestVersion = manifest.version

            // Save manifest to disk for next cold start
            try? data.write(to: manifestPath)

            if !toDownload.isEmpty {
                // Download in batches of 4
                await downloadBatch(toDownload)
            }

        } catch {
            // Non-fatal — app works fine with bundle + existing cache
            #if DEBUG
            print("⚠️ Asset manifest sync failed: \(error.localizedDescription)")
            #endif
        }

        hasSynced = true
    }

    /// Clear all cached assets (useful for debugging or freeing disk space)
    func clearCache() {
        memoryCache.removeAll()
        try? FileManager.default.removeItem(at: cacheDirectory)
        try? FileManager.default.createDirectory(at: cacheDirectory, withIntermediateDirectories: true)
    }

    /// Total disk cache size in bytes
    var diskCacheSize: Int {
        let enumerator = FileManager.default.enumerator(at: cacheDirectory, includingPropertiesForKeys: [.fileSizeKey])
        var total = 0
        while let url = enumerator?.nextObject() as? URL {
            let size = (try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0
            total += size
        }
        return total
    }

    // MARK: - Private Helpers

    private func addToMemoryCache(key: String, image: UIImage) {
        // Evict oldest entries if at limit
        if memoryCache.count >= memoryCacheLimit {
            // Remove ~25% of cache (simple eviction)
            let keysToRemove = Array(memoryCache.keys.prefix(memoryCacheLimit / 4))
            for k in keysToRemove {
                memoryCache.removeValue(forKey: k)
            }
        }
        memoryCache[key] = image
    }

    private func diskCacheFile(forKey key: String) -> URL {
        cacheDirectory.appendingPathComponent("\(key).png")
    }

    private func loadFromDiskCache(key: String) -> UIImage? {
        let path = diskCacheFile(forKey: key)
        guard FileManager.default.fileExists(atPath: path.path) else { return nil }
        return UIImage(contentsOfFile: path.path)
    }

    private nonisolated func downloadAndCache(key: String, url: URL) async -> UIImage? {
        do {
            let (data, response) = try await downloadSession.data(from: url)

            guard let httpResponse = response as? HTTPURLResponse,
                  httpResponse.statusCode == 200,
                  let image = UIImage(data: data) else {
                return nil
            }

            // Save to disk cache
            let cachePath = await MainActor.run { diskCacheFile(forKey: key) }
            try? data.write(to: cachePath)

            // Add to memory cache
            await MainActor.run {
                addToMemoryCache(key: key, image: image)
                pendingDownloads = activeDownloads.count
            }

            return image
        } catch {
            return nil
        }
    }

    private func downloadBatch(_ items: [(key: String, url: URL)]) async {
        // Download 4 at a time
        let batchSize = 4
        for batchStart in stride(from: 0, to: items.count, by: batchSize) {
            let batchEnd = min(batchStart + batchSize, items.count)
            let batch = items[batchStart..<batchEnd]

            await withTaskGroup(of: Void.self) { group in
                for item in batch {
                    group.addTask { [weak self] in
                        guard let self else { return }
                        _ = await self.downloadAndCache(key: item.key, url: item.url)
                    }
                }
            }
        }
    }

    private func loadCachedManifest() {
        guard FileManager.default.fileExists(atPath: manifestPath.path),
              let data = try? Data(contentsOf: manifestPath),
              let manifest = try? JSONDecoder().decode(AssetManifestResponse.self, from: data) else {
            return
        }

        for entry in manifest.assets {
            remoteManifest[entry.key] = entry
        }
        manifestVersion = manifest.version
    }

    private func loadBundledManifest() {
        // Load manifest from app bundle (generated by sync-assets.sh, copied into Resources/)
        guard let url = Bundle.main.url(forResource: "asset-manifest", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let manifest = try? JSONDecoder().decode(AssetManifestResponse.self, from: data) else {
            return
        }

        for entry in manifest.assets {
            bundledManifest[entry.key] = entry
        }
    }
}

// MARK: - Models

struct AssetManifestResponse: Decodable {
    let version: String
    let totalAssets: Int
    let assets: [AssetManifestEntry]
}

struct AssetManifestEntry: Decodable {
    let key: String
    let url: String
    let size: Int
    let category: String
    let updatedAt: String?
}
