'use client'

import { useForm, Controller } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { useMemo } from 'react'
import type { ColumnInfo } from '@/types/schema'
import { mapColumnToFieldType } from '@/types/schema'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Switch } from '@/components/ui/switch'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { JsonEditor } from '@/components/forms/json-editor'
import { capitalize } from '@/lib/utils'

interface DynamicFormProps {
  columns: ColumnInfo[]
  initialData?: Record<string, unknown>
  onSubmit: (data: Record<string, unknown>) => void
  isEdit: boolean
  isLoading?: boolean
}

function isAutoGeneratedColumn(col: ColumnInfo): boolean {
  const name = col.column_name.toLowerCase()
  if (name === 'created_at' || name === 'updated_at') return true
  if (
    col.is_primary_key &&
    col.column_default !== null &&
    (col.column_default.includes('uuid_generate') ||
      col.column_default.includes('gen_random_uuid') ||
      col.column_default.includes('nextval'))
  ) {
    return true
  }
  return false
}

function buildZodSchema(columns: ColumnInfo[], isEdit: boolean) {
  const shape: Record<string, z.ZodTypeAny> = {}

  for (const col of columns) {
    if (!isEdit && isAutoGeneratedColumn(col)) continue

    const fieldType = mapColumnToFieldType(col)
    const nullable = col.is_nullable === 'YES'

    let fieldSchema: z.ZodTypeAny

    switch (fieldType) {
      case 'text':
      case 'uuid':
        fieldSchema = z.string()
        if (nullable) fieldSchema = fieldSchema.optional().or(z.literal(''))
        break
      case 'number':
        fieldSchema = z.coerce.number()
        if (nullable) fieldSchema = fieldSchema.optional().or(z.literal(''))
        break
      case 'boolean':
        fieldSchema = z.boolean()
        break
      case 'datetime':
        fieldSchema = z.string()
        if (nullable) fieldSchema = fieldSchema.optional().or(z.literal(''))
        break
      case 'json':
        fieldSchema = z.string().refine(
          (val) => {
            if (!val || !val.trim()) return nullable
            try {
              JSON.parse(val)
              return true
            } catch {
              return false
            }
          },
          { message: 'Invalid JSON' }
        )
        break
      case 'enum':
        if (col.enum_values && col.enum_values.length > 0) {
          fieldSchema = z.enum(col.enum_values as [string, ...string[]])
          if (nullable) fieldSchema = fieldSchema.optional().or(z.literal(''))
        } else {
          fieldSchema = z.string()
        }
        break
      default:
        fieldSchema = z.string().optional()
    }

    shape[col.column_name] = fieldSchema
  }

  return z.object(shape)
}

function getDefaultValues(
  columns: ColumnInfo[],
  initialData: Record<string, unknown> | undefined,
  isEdit: boolean
): Record<string, unknown> {
  const defaults: Record<string, unknown> = {}

  for (const col of columns) {
    if (!isEdit && isAutoGeneratedColumn(col)) continue

    const fieldType = mapColumnToFieldType(col)
    const existing = initialData?.[col.column_name]

    if (existing !== undefined && existing !== null) {
      if (fieldType === 'json') {
        defaults[col.column_name] =
          typeof existing === 'string' ? existing : JSON.stringify(existing, null, 2)
      } else if (fieldType === 'datetime') {
        try {
          const d = new Date(existing as string)
          defaults[col.column_name] = d.toISOString().slice(0, 16)
        } catch {
          defaults[col.column_name] = ''
        }
      } else if (fieldType === 'boolean') {
        defaults[col.column_name] = Boolean(existing)
      } else {
        defaults[col.column_name] = String(existing)
      }
    } else {
      if (fieldType === 'boolean') {
        defaults[col.column_name] = false
      } else {
        defaults[col.column_name] = ''
      }
    }
  }

  return defaults
}

export function DynamicForm({
  columns,
  initialData,
  onSubmit,
  isEdit,
  isLoading,
}: DynamicFormProps) {
  const editableColumns = useMemo(
    () => columns.filter((col) => isEdit || !isAutoGeneratedColumn(col)),
    [columns, isEdit]
  )

  const schema = useMemo(() => buildZodSchema(columns, isEdit), [columns, isEdit])

  const defaults = useMemo(
    () => getDefaultValues(columns, initialData, isEdit),
    [columns, initialData, isEdit]
  )

  const {
    register,
    handleSubmit,
    control,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(schema),
    defaultValues: defaults,
  })

  const handleFormSubmit = (data: Record<string, unknown>) => {
    const cleaned: Record<string, unknown> = {}

    for (const col of editableColumns) {
      const fieldType = mapColumnToFieldType(col)
      const val = data[col.column_name]

      // Skip auto-generated columns on edit too (PK is read-only)
      if (isEdit && col.is_primary_key) continue

      // Skip empty optional fields
      if ((val === '' || val === undefined) && col.is_nullable === 'YES') {
        cleaned[col.column_name] = null
        continue
      }

      if (fieldType === 'json' && typeof val === 'string' && val.trim()) {
        try {
          cleaned[col.column_name] = JSON.parse(val)
        } catch {
          cleaned[col.column_name] = val
        }
      } else if (fieldType === 'datetime' && typeof val === 'string' && val) {
        cleaned[col.column_name] = new Date(val).toISOString()
      } else if (fieldType === 'number' && val !== '' && val !== undefined) {
        cleaned[col.column_name] = Number(val)
      } else {
        cleaned[col.column_name] = val
      }
    }

    onSubmit(cleaned)
  }

  return (
    <form onSubmit={handleSubmit(handleFormSubmit)} className="space-y-4">
      {editableColumns.map((col) => {
        const fieldType = mapColumnToFieldType(col)
        const isDisabled =
          isEdit && col.is_primary_key && isAutoGeneratedColumn(col)
        const error = errors[col.column_name]

        return (
          <div key={col.column_name} className="space-y-1.5">
            <Label htmlFor={col.column_name} className="flex items-center gap-1.5">
              {capitalize(col.column_name)}
              {col.is_nullable === 'NO' && !isAutoGeneratedColumn(col) && (
                <span className="text-destructive">*</span>
              )}
              {col.is_primary_key && (
                <span className="text-xs text-primary">(PK)</span>
              )}
              {col.is_foreign_key && (
                <span className="text-xs text-warning">
                  (FK: {col.foreign_table})
                </span>
              )}
            </Label>

            {fieldType === 'boolean' ? (
              <Controller
                name={col.column_name}
                control={control}
                render={({ field }) => (
                  <div className="flex items-center gap-2">
                    <Switch
                      checked={field.value as boolean}
                      onCheckedChange={field.onChange}
                      disabled={isDisabled}
                    />
                    <span className="text-sm text-muted-foreground">
                      {field.value ? 'true' : 'false'}
                    </span>
                  </div>
                )}
              />
            ) : fieldType === 'json' ? (
              <Controller
                name={col.column_name}
                control={control}
                render={({ field }) => (
                  <JsonEditor
                    value={(field.value as string) || ''}
                    onChange={field.onChange}
                    disabled={isDisabled}
                  />
                )}
              />
            ) : fieldType === 'enum' && col.enum_values ? (
              <Controller
                name={col.column_name}
                control={control}
                render={({ field }) => (
                  <Select
                    value={field.value as string}
                    onValueChange={field.onChange}
                    disabled={isDisabled}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder={`Select ${col.column_name}`} />
                    </SelectTrigger>
                    <SelectContent>
                      {col.enum_values!.map((val) => (
                        <SelectItem key={val} value={val}>
                          {val}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                )}
              />
            ) : fieldType === 'datetime' ? (
              <Input
                id={col.column_name}
                type="datetime-local"
                disabled={isDisabled}
                {...register(col.column_name)}
              />
            ) : fieldType === 'number' ? (
              <Input
                id={col.column_name}
                type="number"
                step="any"
                disabled={isDisabled}
                placeholder={col.column_name}
                {...register(col.column_name)}
              />
            ) : (
              <Input
                id={col.column_name}
                type="text"
                disabled={isDisabled}
                placeholder={col.column_name}
                {...register(col.column_name)}
              />
            )}

            {error && (
              <p className="text-xs text-destructive">
                {error.message as string}
              </p>
            )}
          </div>
        )
      })}

      <div className="flex justify-end pt-4">
        <Button type="submit" disabled={isLoading}>
          {isLoading ? 'Saving...' : isEdit ? 'Update Record' : 'Create Record'}
        </Button>
      </div>
    </form>
  )
}
